--- #YAML:1.0
name:               Text-Aligner
version:            0.05
abstract:           Align text in columns
author:
    - Anno Siegel (siegel@zrz.tu-berlin.de)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::ANSIColor:  2.01
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
